### ISSUE TITLE
[8.0] product_container : Why does this depend on Indian Localisation?

### ISSUE THREAD

**Issue by lukebranch** [Odoo-India/odoo-india#12]
Thank you for building the product_container module, it's looks like it is very useful to me. Unfortunately it's connected to Indian localisation and therefore it installs a number of other features that are not necessary for me.

Is there any way to remove the dependency to l10n_in_base so that I only have the product_container features independent from the Indian localisation?

If you have time I would appreciate any insight or advice you can offer.

**Comment by mga-odoo** [comment]
It is difficult to identify what you need just looking at the module name or code instead better to enable or disable settings 
![l10n-in-base](https://cloud.githubusercontent.com/assets/7595796/8982272/4287dd1c-36dd-11e5-8ef7-45d32e8305e9.png)

just select what you want to enable and apply settings it will install required module and you will get what you want. l10n_in_base is just installing this settings page and nothing else

so, we prefer to install setting page if you install any module from this repository, it will be easier to mange what you want, may be it has a mane like Indian Localisation but it has some generic features too
