### ISSUE TITLE
Indent management related apps are not working

### ISSUE THREAD

**Issue by kirthiss** [Odoo-India/odoo-india#13]
I tried to install indent management related modules (stock_indent, l10n_in_warehouse ) in both ver 7 and ver 8. Both the times the installation didnt go through. I tried to install it form the web client. 

The error messages are differnt - 'missing modules. Module Product_container missing' or module 'Stock_sale_container' is currently unavailable etc.

Can you please help?

**Comment by azzougouagh** [comment]
Hi,
u need to install Product_container Module

**Comment by mga-odoo** [comment]
It will be more easier to install first l10n_in_base module and from Indian Localisation under settings enable option "Manage internal requests for material, service through Indents." and apply setting. this will install all dependencies.
