### ISSUE TITLE
Missing Tax Mapping

### ISSUE THREAD

**Issue by GeertSurkijn** [Odoo-India/odoo-india#15]
Hello,

which addon includes the tax mapping aka fiscal position data for inter regional invoicing and different tax rules?

**Comment by mga-odoo** [comment]
rather to point module i prefer you to install l10n_in_base, go to Indian Localisation and select the option " Maintain Register of Forms to be issue and to be receive for Inter-State, Intet-Warehouse or Export Sales" under Finance and it will install related module(s).
