### ISSUE TITLE
bcc address is showing to all recipients when using email_cc_bcc module

### ISSUE THREAD

**Issue by omalbastin** [Odoo-India/odoo-india#3]
HI,
I have tested the module email_cc_bcc module. bcc address is showing to all recipients. To Recreating the issue:After configuring outgoing mail correctly, In the sale quotation, at the time of sending email to recipients, add cc and bcc address also(all address are different). Then sent the mail. When I receive the mail, I can see all the receipients(comes under different category to, cc, bcc).I have checked with every addresses.

**Comment by mga-odoo** [comment]
this module is not useful, so removed from this repo.
